### ISSUE TITLE
1.18.2 Compatibility

### ISSUE THREAD

**Issue by sphings79** [wowkster/BedrockMiner#12]
**Is your feature request related to a problem? Please describe.**
1.18.2 compatibility

**Describe the solution you'd like**
1.18.2 compatibility

**Describe alternatives you've considered**
no alternative

**Additional context**
I think tahts not needed :)

**Comment by wowkster** [comment]
As far as I know, it should work just fine on 1.18.2

The config allows you to change the layers so just make it -64

If that doesn't work then let me know

**Comment by sphings79** [comment]
```
[07:44:14 INFO]: _sphings_ issued server command: /bedrockminer give _sphings_
[07:44:14 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bedrockminer' in plugin BedrockMiner v2.0.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2306) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2117) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Duplicate recipe ignored with ID bedrockminer:bedrock_pickaxe
	at net.minecraft.world.item.crafting.RecipeManager.addRecipe(RecipeManager.java:91) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftShapedRecipe.addToCraftingManager(CraftShapedRecipe.java:58) ~[paper-1.18.2.jar:git-Paper-267]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.addRecipe(CraftServer.java:1411) ~[paper-1.18.2.jar:git-Paper-267]
	at org.bukkit.Bukkit.addRecipe(Bukkit.java:959) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at com.adrianwowk.bedrockminer.BedrockPickaxe.initPickaxe(BedrockPickaxe.java:206) ~[BedrockMiner-v2.0.0.jar:?]
	at com.adrianwowk.bedrockminer.BedrockPickaxe.getItem(BedrockPickaxe.java:211) ~[BedrockMiner-v2.0.0.jar:?]
	at com.adrianwowk.bedrockminer.commands.CommandHandler.onCommand(CommandHandler.java:49) ~[BedrockMiner-v2.0.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	... 21 more
```
```
version
[07:47:29 INFO]: Checking version, please wait...
[07:47:29 INFO]: This server is running Paper version git-Paper-267 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a)
You are running the latest version
Previous version: git-Paper-265 (MC: 1.18.2)
version bedrockminer
[07:47:34 INFO]: BedrockMiner version 2.0.0
[07:47:34 INFO]: Author: Adrian Wowk
```

**Comment by wowkster** [comment]
Ok I will look into it.

Thanks for letting me know
