### ISSUE TITLE
null error in console

### ISSUE THREAD

**Issue by mrfloris** [wowkster/BedrockMiner#2]
```
[05:18:24 ERROR]: Could not pass event PlayerInteractEvent to BedrockMiner v1.5.6
java.lang.IllegalArgumentException: Cannot translate null text
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.5.jar:git-Paper-442]
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[patched_1.16.5.jar:git-Paper-442]
	at com.adrianwowk.bedrockminer.BedrockMiner.translate(BedrockMiner.java:90) ~[?:?]
	at com.adrianwowk.bedrockminer.events.BedrockMinerEvents.onLeftClick(BedrockMinerEvents.java:70) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor17.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-442]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-442]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-442]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-442]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:511) ~[patched_1.16.5.jar:git-Paper-442]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:474) ~[patched_1.16.5.jar:git-Paper-442]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:469) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:154) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1485) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.5.jar:git-Paper-442]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-442]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
```
> ver
[05:20:10 INFO]: This server is running Paper version git-Paper-442 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[05:20:10 INFO]: Checking version, please wait...
[05:20:11 INFO]: You are 1 version(s) behind
> ver BedrockMiner
[05:20:15 INFO]: BedrockMiner version 1.5.6
[05:20:15 INFO]: Author: Adrian Wowk
> pl
[05:20:18 INFO]: Plugins (6): BedrockMiner, CMI, CMILib, CMIPaperLib, LuckPerms, Vault
>
```

**Comment by wowkster** [comment]
Will be fixed in the next release

**Comment by mrfloris** [comment]
Hey there, 

Thank you for being so supportive, and that we narrowed it down to what caused this. Looking forward to the new jar :)

Floris.
